### ISSUE TITLE
App returns white screen on Android X

### ISSUE THREAD

**Issue by StijnWoerkom** [JideGuru/FlutterTravel#10]
I ran this app on an Emulator with Android X. When running this app, it showed a white screen. The installation is successful, everything works but I can't see anything except for a white screen. 

Flutter doctor:
```
[√] Flutter (Channel master, v1.10.15-pre.186, on Microsoft Windows [Version 10.0.18362.719], locale en-US)
    • Flutter version 1.10.15-pre.186 at C:\flutterSDK\flutter
    • Framework revision 1c535de7e0 (5 months ago), 2019-10-18 16:40:42 -0700
    • Engine revision 8aefcd8575
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Stijn van Woerkom\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3
    • Flutter plugin version 40.0.4
    • Dart plugin version 192.6817.14

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Stijn van Woerkom\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

```

**Comment by StijnWoerkom** [comment]
![image](https://user-images.githubusercontent.com/47785402/76681298-eb741b00-65f1-11ea-8a96-f65644ae6df6.png)

**Comment by JideGuru** [comment]
Does it display well without AndroidX

**Comment by StijnWoerkom** [comment]
It only displays the white screen above without AndroidX. If I try to migrate it to AndroidX it says: “No usages found in project. Even when you add AndroidX in the Gradle files.

**Comment by JideGuru** [comment]
Hey, i made an update. can you confirm if it fixes the issue?

**Comment by StijnWoerkom** [comment]
@JideGuru I tried with your latest update, but I didn't see any change. Maybe if you migrate your project to AndroidX it will work. I have tried it myself, but ended with an error statement: "No usages found in project". I have tried to apply the following changes to gradle.properties, but didn't have any luck.

android.useAndroidX=true
android.enableJetifier=true

**Comment by StijnWoerkom** [comment]
@JideGuru I have checked your update and it worked. Thank you for your work. It is a nice app you have build. This issue can now be closed.
