### ISSUE TITLE
isDark variable not found

### ISSUE THREAD

**Issue by ganeshchenniah** [JideGuru/FlutterTravel#13]
Hi,
isDark  is not found in main.dart file and also navigation drawer icon also not visible

**Comment by JideGuru** [comment]
Hello @ganeshchenniah , There is no `isDark` anymore because the app now adapts to the Device's theme.
I just updated the documentation. Can you share a screenshot so I can see where the drawer icon is not showing?

Thanks

**Comment by ganeshchenniah** [comment]
Hi
Pfa

**Comment by JideGuru** [comment]
The Drawer icon was removed as it was not being used
