### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by gsabater** [JideGuru/FlutterTravel#7]
Hello,

on `main.dart` line 3, you import `import 'package:flutter_travel_concept/controller/home_controller.dart';`
but the file is not present in the repository.

Thanks

**Comment by JideGuru** [comment]
Please pull the repo again. Issue is fixed

**Comment by gsabater** [comment]
Hey @JideGuru ,

Looks good now.
I swear I could open the drawer before, and now i can't open it, but at least now i can run the repository without any issues.

Thanks for the demo, awesome job.
